# Generated by Django 4.1.1 on 2022-09-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_tiffin_meetu_alter_tiffin_sami_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiffin',
            name='todays_data',
        ),
    ]
