# Generated by Django 4.1.1 on 2022-09-10 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_tiffin_todays_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='shift',
            field=models.CharField(choices=[('1', 'Morning'), ('2', 'Night')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='tiffin',
            name='today_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
