# Generated by Django 4.1.1 on 2022-09-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='meetu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='sami',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='utsi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='vanshi',
            field=models.FloatField(default=0),
        ),
    ]
