# Generated by Django 4.1.1 on 2022-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_tiffin_meetu_alter_tiffin_sami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='meetu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='sami',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='utsi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='vanshi',
            field=models.IntegerField(default=0),
        ),
    ]
