# Generated by Django 4.1.1 on 2022-09-14 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_tiffin_meetu_alter_tiffin_sami_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
