# Generated by Django 4.1.1 on 2022-09-14 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_todo_list_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='payday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
